# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

strategy:
  matrix:
    Python27:
      python.version: '2.7'
      imageName: 'ubuntu-16.04'
    Python34:
      python.version: '3.4'
      imageName: 'ubuntu-16.04'
    Python35:
      python.version: '3.5'
      imageName: 'ubuntu-16.04'
    Python36:
      python.version: '3.6'
      imageName: 'ubuntu-16.04'
    Python37:
      python.version: '3.7'
      imageName: 'ubuntu-16.04'
    Mac_Python27:
      python.version: '2.7'
      imageName: 'macos-10.13'
    Mac_Python37:
      python.version: '3.7'
      imageName: 'macos-10.13'
    Windows_Python27:
      python.version: '2.7'
      imageName: 'vs2017-win2016'
    Windows_Python37:
      python.version: '3.7'
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    git config --global user.email user@example.com
    git config --global user.name "Example User"
  displayName: 'Configure git user/email'

- script: |
    python -m pip install --upgrade pip
    pip install -r dev-requirements.txt
    pip install -r requirements.txt
    python setup.py develop
    pip install pytest pytest-azurepipelines pytest-cov coveralls
  displayName: 'Install dependencies'

- script: |
    pytest PyGitUp/tests --cov=PyGitUp --cov-report=html:$(Build.SourcesDirectory)/htmlcov
  displayName: 'Run tests'

- script: |
    coveralls
  displayName: 'Upload test coverage'
  env:
    COVERALLS_REPO_TOKEN: $(token.coveralls)